# Generated by Django 4.2.5 on 2023-09-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_autor_data_nascimento_autor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='idade',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
