# Generated by Django 4.2.5 on 2023-10-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_autor_idade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nome_Autor',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='data_Nascimento',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(default='1980-01-01'),
        ),
    ]
