# Generated by Django 4.2.5 on 2023-10-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_rename_nome_autor_autor_nome_remove_autor_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
