# Generated by Django 4.2.6 on 2023-11-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0006_alter_autor_options_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(default='1980-01-01', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='idade',
            field=models.PositiveSmallIntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(blank=True, verbose_name='Conteudo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_pub',
            field=models.DateField(blank=True, null=True, verbose_name='Data da publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titulo'),
        ),
    ]
