# Generated by Django 4.2.6 on 2023-11-30 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticia', '0008_alter_autor_options_alter_autor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário:'),
        ),
    ]
